### ISSUE TITLE
new paper that uses phoebe – for publications page

### ISSUE THREAD

**Issue by podesse** [phoebe-project/phoebe-project.org#5]
We published a paper earlier this year that uses PHOEBE 2.3, which we hope other PHOEBE users will find useful!

Here is the ADS link, in case you would like to add it to the Publications page of the PHOEBE website.
https://ui.adsabs.harvard.edu/abs/2022ApJ...926...46O/abstract

**Comment by kecnry** [comment]
Congrats on the paper!  I'll make sure to list it (and close out this issue) the next time I get around to updating the list.
