### ISSUE TITLE
new paper that uses phoebe

### ISSUE THREAD

**Issue by ayushmoharana** [phoebe-project/phoebe-project.org#7]
@ARTICLE{2023MNRAS.521.1908M,
       author = {{Moharana}, Ayush and {He{\l}miniak}, K.~G. and {Marcadon}, F. and {Pawar}, T. and {Konacki}, M. and {Ukita}, N. and {Kambe}, E. and {Maehara}, H.},
        title = "{Detached eclipsing binaries in compact hierarchical triples: triple-lined systems BD+442258 and KIC 06525196}",
      journal = {\mnras},
     keywords = {binaries: eclipsing, binaries: spectroscopic, stars: evolution, stars: fundamental parameters, stars: individual: BD+44 2258, KIC 06525196, stars: kinematics and dynamics, Astrophysics - Solar and Stellar Astrophysics},
         year = 2023,
        month = may,
       volume = {521},
       number = {2},
        pages = {1908-1923},
          doi = {10.1093/mnras/stad622},
archivePrefix = {arXiv},
       eprint = {2303.05272},
 primaryClass = {astro-ph.SR},
       adsurl = {https://ui.adsabs.harvard.edu/abs/2023MNRAS.521.1908M},
      adsnote = {Provided by the SAO/NASA Astrophysics Data System}
}

**Comment by kecnry** [comment]
Great, congrats!  I haven't updated the list in a little while - so I'll try to get to that soon and will make sure to add this one when I do.
