### ISSUE TITLE
issue with install instructions: 2.4.16/windows/python3

### ISSUE THREAD

**Issue by aliyyanurr** [phoebe-project/phoebe-project.org#9]
Hello,

I have difficulties installing PHOEBE 2.4. It seems like there is an error in installing corner (or maybe other dependencies besides corner). I tried to install [corner](https://github.com/dfm/corner.py) independently but the problem still remains.

Is there any recommendation to solve this?

![image](https://github.com/user-attachments/assets/4442eac1-5f28-4ef8-8e4b-e317e7615206)

**Comment by kecnry** [comment]
it looks like the latest release of corner requires python 3.9.  Can you try installing corner 2.2.1 manually and/or try installing in an environment with python 3.9+ and let us know if that resolves the issue?

**Comment by aliyyanurr** [comment]
Hello, thank you for the suggestion.
While creating the new environment with a specific python version, I also rechecked other libraries like pip, setuptools, and the connection and proxy settings (I am using a remote server with proxy). Now the installation works well and I can use PHOEBE using python 3.9.12. Thank you!
